- name: "stop {{component}}" 
  tags: 
   - deployment
  ansible.builtin.service:
    name: "{{component}}"
    state: stopped

- name: Recursively remove app directory
  tags: 
   - deployment
  ansible.builtin.file:
      path: /app
      state: absent

     
- name: creating directory
  ansible.builtin.file:
    path: /app
    state: directory 

- name: "downloading {{component}} application"
  ansible.builtin.get_url:
    url: "https://roboshop-builds.s3.amazonaws.com/{{component}}.zip"
    dest: /tmp 

- name: "extract {{component}}"
  ansible.builtin.unarchive:
    src: "/tmp/{{ component}}.zip"
    dest: /app
    remote_src: yes