- name: install golang
  ansible.builtin.dnf: 
      name: golang
      state: present

      
- name: build go application
  ansible.builtin.command: "{{items}}"
  loop:
   - go mod init dispatch
   - go get
   - go build
  args:
    chdir: /app
