  - name: Copy mongo repo
    ansible.builtin.copy:
      src: mongo.repo
      dest: /etc/yum.repos.d/mongo.repo

  - name: Install mongodb client
    ansible.builtin.package:
       name: mongodb-org-shell
       state: present
    

  - name: gets the catageries count
    ansible.builtin.command: mongo --host mongodb.devopsrank.online --quiet --eval 'db = db.getSiblingDB("catalogue"); db.products.count()'
    register: product_count

  # - name: print the count
  #   ansible.builtin.debug:
  #     msg: "product count is {{ product_count }}"

  - name: load catalogue
    ansible.builtin.command: mongo --host mongodb.devopsrank.online < /app/schema/catalogue.js   
    when: product_count.stdout == "0" 